version: '3'
services:
  web:
    build: front 
    ports:
      - 3000:3000
    environment:
        - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes